Pandas,Numpy_Lecture_01.pdf

# Numpy 사용해보기

## 1. NumPy 소개
- Numerical Python
- 대규모 다차원 배열을 다룸
- 빠른 연산과 메모리를 효율적으로 사용


### (1) 배열 만들기

In [1]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
import numpy as np

np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
np.array([3,1.4,2,3,4]) # 하나라도 실수 있으면 맞춰줌

array([3. , 1.4, 2. , 3. , 4. ])

In [5]:
np.array([[1,2],
         [3,4]])

array([[1, 2],
       [3, 4]])

In [6]:
np.array([1,2,3,4], dtype='float')

array([1., 2., 3., 4.])

### (2) 배열 데이터 타입 dtype

In [7]:
arr = np.array([1,2,3,4], dtype=float)
arr

array([1., 2., 3., 4.])

In [8]:
arr.dtype

dtype('float64')

In [9]:
# 배열 데이터 타입 바꿀 때: .astype()
arr.astype(int) 

array([1, 2, 3, 4])

| dtype | 설명 | 표현 |
|:----------|:----------:|----------:|
| int | 정수형 타입 | i, int_, int32, int64, i8 |
| float | 실수형 타입 | f, float_, float32, float64, f8 |
| str | 문자열 타입 | str, U, U32 |
| bool | 불 타입 | ?, bool_ |

### (3) 다양한 배열 만들기

In [10]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [11]:
np.ones((4, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.arange(0, 25, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [13]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### (4) 난수로 채워진 배열 만들기

In [14]:
np.random.random((5, 5))

array([[0.17414177, 0.58979054, 0.30439777, 0.3878489 , 0.93307809],
       [0.87891861, 0.50376435, 0.23778945, 0.1211591 , 0.65344145],
       [0.57336072, 0.78544321, 0.58014403, 0.93696469, 0.74419949],
       [0.70908102, 0.11079155, 0.1878881 , 0.43847255, 0.70153753],
       [0.06024712, 0.32465493, 0.39202113, 0.80582669, 0.16763088]])

In [15]:
np.random.normal(0, 1, (2, 2))

array([[-0.65112082,  0.55980554],
       [-0.31542155,  1.43736306]])

In [16]:
np.random.randint(0, 10, (2, 2))

array([[4, 9],
       [6, 8]])

### (5) 배열의 기초

In [17]:
x2 = np.random.randint(10, size=(3, 4))
x2

array([[6, 1, 0, 1],
       [3, 3, 7, 1],
       [7, 7, 5, 9]])

In [18]:
x2.ndim # 차원

2

In [19]:
x2.shape # 모양

(3, 4)

In [20]:
x2.size # 크기

12

In [21]:
x2.dtype # 데이터 타입

dtype('int32')

판다스에서 많이 봐.\
타임시리즈?\
linspace: 공간을 표현하겠다

In [22]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
np.linspace(0,3,3)

array([0. , 1.5, 3. ])

랜덤함수(많이 씀)

In [24]:
np.random.random((2,2))

array([[0.63122391, 0.06439095],
       [0.72744843, 0.09715037]])

In [25]:
np.random.normal(0,1,(2,2))

array([[-0.46294483, -0.50376807],
       [ 0.55180941, -0.53557928]])

In [26]:
np.random.randint(0,10,(2,2))

array([[4, 7],
       [6, 7]])

In [28]:
np.random.randint(0,10,(3,2))# 크기가 정해져있으면 에러 뜰 수  있는데 이건 랜덤이니까

array([[6, 4],
       [3, 9],
       [6, 3]])

이건 가상환경이랑 연결. 인공지능과 VR과 연결돼. 융합될 수 밖에. 지금은 산업과 인공지능이 연결되고 있음.

배열의 기초

In [32]:
x2=np.random.randint(10, size=(3,4))
x2

array([[7, 3, 6, 2],
       [8, 7, 1, 4],
       [0, 7, 6, 1]])

In [34]:
x2.ndim # n차원?

2

In [35]:
x2.shape

(3, 4)

In [38]:
x2.size #원소개수 12개

12

In [39]:
x2.dtype

dtype('int32')

## 2. 인덱싱 / 슬라이싱
### (1) Indexing: 인덱스로 값을 찾기

In [22]:
x = np.arange(7)
x

array([0, 1, 2, 3, 4, 5, 6])

In [23]:
x[3]

3

In [24]:
x[7]

IndexError: index 7 is out of bounds for axis 0 with size 7

In [25]:
x[0] = 10
x

array([10,  1,  2,  3,  4,  5,  6])

### (2) Slicing: 인덱스 값으로 배열의 부분을 가져오기

In [26]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [27]:
x[1:4] # 4자리는 n-1까지 출력해달라는 것.

array([1, 2, 3])

In [28]:
x[1:]

array([1, 2, 3, 4])

In [29]:
x[:4]

array([0, 1, 2, 3])

In [30]:
x[::2] # ::step

array([0, 2, 4])

### (3) reshape으로 모양 바꾸기

In [31]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [32]:
x.shape #세로로 행 표기가 안됨. 

(8,)

In [33]:
x2=x.reshape((2,4))
x2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [35]:
x2.shape

(2, 4)

In [36]:
x.size

8

In [37]:
x2.size

8

### (4) concatenate: 배열을 이어 붙임

In [38]:
x=np.array([0,1,2])
x

array([0, 1, 2])

In [39]:
y=np.array([3,4,5])
y

array([3, 4, 5])

In [40]:
np.concatenate([x,y])

array([0, 1, 2, 3, 4, 5])

 - axis 축을 기준으로 이어 붙임

In [41]:
mat = np.arange(4)
mat

array([0, 1, 2, 3])

In [42]:
mat = np.arange(4).reshape(2,2)
mat

array([[0, 1],
       [2, 3]])

In [43]:
np.concatenate([mat,mat], axis=0) # 행 기준으로 합치기

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [44]:
np.concatenate([mat,mat], axis=1) # 열 기준으로 합치기

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

### (5) split: 나누기

In [45]:
mat1=np.arange(16).reshape(4,4)
mat1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
upper, lower=np.split(mat1, [2], axis=0) # 0이니까 행 기준 [2]
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [47]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
left, right=np.split(mat1, [2], axis=1) #1이니까 열 기준 [2]
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [49]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [50]:
matrix = np.arange(16).reshape(4, 4)
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
upper, lower = np.split(matrix, [3], axis=0)
upper

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
lower

array([[12, 13, 14, 15]])

In [53]:
matrix = np.arange(16).reshape(4, 4)
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
left, right = np.split(matrix, [3], axis=1)
left

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [55]:
right

array([[ 3],
       [ 7],
       [11],
       [15]])

## 3. numpy 연산
### (1) array의 모든 원소에 5를 더한 함수

In [56]:
def add_five_to_array(values):
    output=np.empty(len(values)) # 엠티는 제로랑 달라, 0에 가깝다
    for i in range(len(values)):
        output[i] = values[i]+5
    return output

values = np.random.randint(1,10,size=5)
add_five_to_array(values)

array([11.,  9.,  7., 12.,  7.])

In [57]:
np.empty([2,2])

array([[ 2.12199579e-314, -5.08377619e+058],
       [ 2.41104035e-321,  6.95293141e-310]])

#### np.empty():
- 빈 공간과 같음. 제로와는 다름. 
- 비어있는 값인데 그 안에는 밸류 세팅할 수 있게끔 값을 줌.
- 빈 리스트로 나눠주되, 랜덤하게 무한대와 -무한대와 가깝게 가까운 값을 줌.
- 타입을 바꿔줄 수 있음.

In [58]:
big_array = np.random.randint(1, 100, size=10000000)
big_array

array([74,  6, 97, ..., 16,  5, 68])

In [59]:
add_five_to_array(big_array)

array([ 79.,  11., 102., ...,  21.,  10.,  73.])

In [60]:
big_array + 5

array([ 79,  11, 102, ...,  21,  10,  73])

In [87]:
values

array([8, 3, 5, 2, 5])

In [89]:
len(values) # 인덱스로 접근. 

5

### (2) array의  +,-,*,/ 기본 연산

In [61]:
x=np.arange(4)
x

array([0, 1, 2, 3])

In [62]:
x+5

array([5, 6, 7, 8])

In [63]:
x-5

array([-5, -4, -3, -2])

In [64]:
x*5

array([ 0,  5, 10, 15])

In [65]:
x/5

array([0. , 0.2, 0.4, 0.6])

### (3) 다차원 행렬 간 연산

In [66]:
x=np.arange(4)
x

array([0, 1, 2, 3])

In [67]:
x=np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [68]:
y=np.random.randint(10, size=(2,2))
y

array([[0, 5],
       [6, 7]])

In [69]:
x+y

array([[ 0,  6],
       [ 8, 10]])

In [70]:
x-y

array([[ 0, -4],
       [-4, -4]])

### (4) 브로드캐스팅
- 모양(shape)가 다른 배열끼리 연산

In [71]:
np.arange(3) #세로행

array([0, 1, 2])

In [72]:
np.arange(3).reshape((3,1)) #모양 바꾸기 - 3행 1열

array([[0],
       [1],
       [2]])

In [73]:
np.arange(3).reshape((3,1))+np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [74]:
arr3 = np.arange(3).reshape((3,1))+np.arange(3)
arr3

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [75]:
arr3 + 5

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

## 4. 집계함수 & 마스킹 연산

### (1) 집계:
- 데이터에 대한 요약 통계

In [76]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
x= np.arange(10).reshape((2,5))
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
np.sum(x)

45

In [79]:
np.min(x)

0

In [80]:
np.max(x)

9

In [81]:
np.mean(x) # 평균값

4.5

In [82]:
28/8

3.5

In [83]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [84]:
np.sum(x, axis=0) # 0은 행 기준, 열끼리 나오겠지. 같은 열끼리 더하니까

array([ 5,  7,  9, 11, 13])

In [85]:
np.sum(x, axis=1) # 1은 열 기준, 행을 다 더하니까

array([10, 35])

- axis=0은 행 기준이니까 열에 있는 값을 더해주고 결과가 열로 나옴

### (2) 마스킹 연산:
- Boolean array를 통해 특정 값 뽑을 때

In [86]:
x= np.arange(5)
x

array([0, 1, 2, 3, 4])

In [87]:
np.sum(x, axis=0)

10

In [88]:
x<3

array([ True,  True,  True, False, False])

In [89]:
x>4

array([False, False, False, False, False])

In [90]:
x[x<3]

array([0, 1, 2])

--- seYi